FROM python:3.8-slim-buster

RUN pip install -U pip
RUN pip install pipenv
WORKDIR /app

COPY [ "Pipfile.lock", "./"]

RUN pipenv install --system --deploy

COPY ["deploy/app.py", "app.py"]
COPY ["deploy/load.py", "load.py"]

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
